import 'package:flutter/material.dart';

List<IconData> icons = [
  const IconData(0xe559, fontFamily: 'MaterialIcons'),
  const IconData(0xe189, fontFamily: 'MaterialIcons'),
  const IconData(0xe55a, fontFamily: 'MaterialIcons'),
  const IconData(0xe5e8, fontFamily: 'MaterialIcons'),
  const IconData(0xe56f, fontFamily: 'MaterialIcons'),
  const IconData(0xe5f2, fontFamily: 'MaterialIcons'),
  const IconData(0xe313, fontFamily: 'MaterialIcons'),
  const IconData(0xe090, fontFamily: 'MaterialIcons'),
  const IconData(0xe5e6, fontFamily: 'MaterialIcons'),
  const IconData(0xe5f3, fontFamily: 'MaterialIcons'),
  // const IconData(0xf06c3, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5ed, fontFamily: 'MaterialIcons'),
  // const IconData(0xe622, fontFamily: 'MaterialIcons'),
  // const IconData(0xe4be, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5f4, fontFamily: 'MaterialIcons'),
  // const IconData(0xf056f, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5e5, fontFamily: 'MaterialIcons'),
  // const IconData(0xe200, fontFamily: 'MaterialIcons'),
  // const IconData(0xe350, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5eb, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5e9, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5bc, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5ea, fontFamily: 'MaterialIcons'),
  // const IconData(0xe5e7, fontFamily: 'MaterialIcons'),
  // const IconData(0xe441, fontFamily: 'MaterialIcons'),
  // const IconData(0xf06c0, fontFamily: 'MaterialIcons'),
  // const IconData(0xe35f, fontFamily: 'MaterialIcons'),
  // const IconData(0xe543, fontFamily: 'MaterialIcons'),
  // const IconData(0xf06c2, fontFamily: 'MaterialIcons'),
];