// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTU__TcYtV_YkyxGzUBCrt7KFIu9_-EQg',
    appId: '1:250643361626:web:3fe581af109e2c2a1a0d63',
    messagingSenderId: '250643361626',
    projectId: 'streak-bec7c',
    authDomain: 'streak-bec7c.firebaseapp.com',
    storageBucket: 'streak-bec7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAMuZ38-bjlWK7znw8S1lJLqrKTX7FrCI',
    appId: '1:250643361626:android:71947f64c87668661a0d63',
    messagingSenderId: '250643361626',
    projectId: 'streak-bec7c',
    storageBucket: 'streak-bec7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5qC8SOJbgCqUqRk7BFLIGBOiKL2K_UwI',
    appId: '1:250643361626:ios:6927f4da1ac3a1ca1a0d63',
    messagingSenderId: '250643361626',
    projectId: 'streak-bec7c',
    storageBucket: 'streak-bec7c.appspot.com',
    iosClientId: '250643361626-ukdqb6nrc91rr8nm9mjj7sf11fidio8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.streak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5qC8SOJbgCqUqRk7BFLIGBOiKL2K_UwI',
    appId: '1:250643361626:ios:6927f4da1ac3a1ca1a0d63',
    messagingSenderId: '250643361626',
    projectId: 'streak-bec7c',
    storageBucket: 'streak-bec7c.appspot.com',
    iosClientId: '250643361626-ukdqb6nrc91rr8nm9mjj7sf11fidio8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.streak',
  );
}
